### PR TITLE
Update StudentSolutions.sql

### PR DESCRIPTION
**Pull request by 123medini**
My solution to the Challenge - Identify breeds that were never adopted

### CODE REVIEW

**Comment by 123medini** [comment]
My solution to the Challenge - Identify breeds that were never adopted

**Review by ami-levin — CHANGES_REQUESTED** [review]
Hi Medini and thanks for uploading your solution!
Before we merge it, there are a few minor issues to fix:
1. Remove the ORDER BY on row 37.
2. Add species to row 29
3. There is a minor logical bug with your solution which is not obvious with the current data set. Try to see if you can find it by adding the following animal and executing both the original solution and yours, and compare the results.
-- Add Ferris, the non breed ferret that wasn't adopted
INSERT INTO Animals
(Name, Species, Primary_Color, Implant_Chip_ID, Breed, Gender, Birth_Date, Pattern, Admission_Date)
VALUES ('Ferris', 'Ferret', 'White', 'A0EEBC99-9C0B-4EF8-BB6D-6BB9BD380A11', NULL, 'F', '20161122', 'Solid', '20171221');
Let me know if you need a hint :-)

**Comment by 123medini** [comment]
Hi Ami,

Thanks for your reply. I truly appreciate it.

I understand what you are trying to say regarding the bug but I am very
happy to confirm that the query works and gives the correct output even
when I include Ferris :)
I think it works because I used distinct in the derived table.
1) When I left join animals with adoptions in a CTE, I used  a case
operator to assign 0 wherever the adoption_date was null and 1 where the
adoption_date was available. 
2) Then in the derived table I used window function to sum up all the 1s
and as I used distinct for species and breed, it worked like group by and
as there is a single row for ferret and it did not have an adoption_date,
the sum of the breed (Null in this case) was 0 and that's how it got picked
up along with Turkish Angora cats.

Does that make sense? Your inputs on this logic would be greatly
appreciated.

I want to add that the way you explain the solution for the challenge and
your Demo bits while explaining the concept work so well to make the
concept clear.

Thanks again

Warm regards,
Medini

**Comment by ami-levin** [comment]
Hi Medini,
The solution doesn't work currently.
1. You need to remove the ORDER BY from the subquery on row 37.
2. Add species to the select list on row 29 - it is required to identify the breed, we can have non-breed dogs and non-breed cats, or domestic rabbit and domestic ferrets.
3. Your solution does not return Ferris when I execute it. It's a small issue, you should be able to spot it (hint - see 2...) 
Ami

**Comment by 123medini** [comment]
Oh ok. Thanks Ami. I will definitely try again. Must have missed something.

Warm regards,
Medini

**Comment by 123medini** [comment]
Hi Ami,

I tried again. I am getting ferret  in the output. I added species as
suggested by you.
[image: image.png]

Hope this is ok now:)

Thanks for the inputs.

Warm regards,
Medini

**Comment by ami-levin** [comment]
Can you make the changes in your Pull Request and commit so I can see them? the image doesn't show up... You also need to make the change as I assigned you with a change request.

**Comment by ami-levin** [comment]
Hi Medini,
Sorry for the hassle, but can you make the changes on this PR and not on a new one?
This will retain our conversation.
I see that you fixed items 1 and 2, but there is still a small bug in your code.
If you give up trying to find it, let me know and I'll explain it 👍 
Be safe!

**Comment by 123medini** [comment]
Hi Ami,

I am so sorry for this confusion about new PR. Actually I am new to this PR
thing and taking time to figure it out.
The query worked in MySQL but if you say there is still a bug, I will try
and fix it. Can you pls give me a hint though :)

Thanks again.

Warm regards,
Medini

**Comment by ami-levin** [comment]
No worries! 
I still find GitHub workflow confusing on my best day :-)
The query would not work in SQL Server and many other DBs as ORDER BY is not allowed in sub queries unless used with LIMIT / FETCH. If MySQL doesn't complain about this syntax, it means it just ignores the ORDER BY.
As for adding Species to the SELECT list, it was part of the requirement. An animal is identified by name AND species, so name is not enough.
Your query fails to get back Ferris. See the 2 queries before and after adding Ferris here: https://dbfiddle.uk/?rdbms=postgres_12&fiddle=c06e1c65670463a1fe02aabe30544ae3&hide=1
This is using PostgreSQL, but the idea is the same.
See you your query doesn't return Ferris?
HINT - Breed is feeling lonely.  By itself, it can't identify the type of animal..
We can have "Domestic" breed cats, but also "Domestic" breed dogs which are not the same... 
Perhaps a domestic dog was never adopted but a domestic cat was? 
Same is true for NULL breed, or "No breed" Ferris...

**Comment by 123medini** [comment]
Wow... that hint is a good one. So we are trying to identify breeds that
were never adopted in general and not per species, is that correct? This
makes it exciting. The strange thing is MYSQL is returning Ferret for my
query but looks like Postgres is not that kind:)

Anyways thanks for taking the time to explain to me where I might be making
a mistake. I will think about it and modify the query.

Warm regards,
Medini

**Comment by 123medini** [comment]
Hi Ami,

Got tied up and so couldn't work on this. I have modified the code and let
us see if that works now. I have now partitioned the data as per species
and breed (earlier it was partitioned only as per breed)

Thanks so much Ami for your time. It has helped me clarify a lot of my
concepts . Now I can go back to completing the rest of your course on
Logical Query Processing - Part 2

Warm Regards,
Medini

**Review by ami-levin — APPROVED** [review]

**Comment by ami-levin** [comment]
Excellent. 
I will merge these changes now.
Nice work! If you add a bit more explanation how you came up with this solution or how it works, I'm sure others will appreciate it. 
No pressure :-) Totally optional. You've done more than most already 👍

**Comment by 123medini** [comment]
Thanks Ami. I will post an explanation as well.

Warm regards,
Medini

**Pull request merged**
